#ifndef TINYTASKS_CONFIG_H
#define TINYTASKS_CONFIG_H

#include <stdint.h>
#define SYSTEM_CLCOCK_FREQ_MHZ 80
#define TINYTASKS_MAX_TASKS  3
#define TINYTASKS_STACK_SIZE 512

#endif // TINYTASKS_CONFIG_H
