#ifndef TINYTASKS_CONFIG_H
#define TINYTASKS_CONFIG_H

#include <stdint.h>

#define TINYTASKS_MAX_TASKS  3
#define TINYTASKS_STACK_SIZE 512
#define TOTAL_STACK_SIZE (TINYTASKS_MAX_TASKS * TINYTASKS_STACK_SIZE)



#endif // TINYTASKS_CONFIG_H
