#ifndef TINYTASKS_CONFIG_H
#define TINYTASKS_CONFIG_H

#include <stdint.h>
#define SYSTEM_CLCOCK_FREQ_MHZ 80
#define TINYTASKS_NUMBER_OF_TASKS  2
#define TINYTASKS_STACK_SIZE 1000
#define TINYTASKS_DEBUG 1


#endif // TINYTASKS_CONFIG_H
